name       : cups-pk-helper
version    : 0.2.6
release    : 5
source     :
    - https://www.freedesktop.org/software/cups-pk-helper/releases/cups-pk-helper-0.2.6.tar.xz : 959af8f2f5a2761e7e498b61c9caf25ae963335031eae9972d999e9a0d97a228
license    : GPL-2.0
component  : desktop.core
summary    : cups PolicyKit helper
description: |
    cups-pk-helper is a PolicyKit helper to configure cups with fine-grained privileges.
builddeps  :
    - cups-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
