name       : cups-pk-helper
version    : 0.2.6
release    : 9
source     :
    - https://www.freedesktop.org/software/cups-pk-helper/releases/cups-pk-helper-0.2.6.tar.xz : 959af8f2f5a2761e7e498b61c9caf25ae963335031eae9972d999e9a0d97a228
license    : GPL-2.0-or-later
component  : desktop.core
summary    : cups PolicyKit helper
description: |
    cups-pk-helper is a PolicyKit helper to configure cups with fine-grained privileges.
builddeps  :
    - cups-devel
    - gnome-common
setup      : |
    %patch -p1 < $pkgfiles/cups-pk-helper_daemon_user_T7453.patch
    # sysconfdir is only used for dbus-1 in /etc so just move it to correct location
    %reconfigure --sysconfdir=/usr/share --with-daemon-user=cups-pk-helper
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/cups-pk-helper.sysusers $installdir/%libdir%/sysusers.d/cups-pk-helper.conf
