name       : cups-pk-helper
version    : 0.2.5
release    : 3
source     :
    - http://www.freedesktop.org/software/cups-pk-helper/releases/cups-pk-helper-0.2.5.tar.xz : 19221eed65a1e1498d396f3f99a783a95b21b4385e63b57a1f16e8728b8ca118
license    : GPL-2.0
summary    : cups PolicyKit helper
description: |
    cups-pk-helper is a PolicyKit helper to configure cups with fine-grained privileges.
builddeps  :
    - cups-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
